name: Build and Deploy Spring API

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy Spring API
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: 17

      - name: Run Unit Tests
        run: mvn -B test --file pom.xml

      - name: SonarQube Scan
        uses: kitabisa/sonarqube-action@v1.2.0
        env:
          SONAR_SCANNER_OPTS: -X
        with:
          host: ${{ secrets.SONARQUBE_HOST }}
          login: ${{ secrets.SONARQUBE_TOKEN }}
          projectBaseDir: "src/"
          projectKey: "my-custom-project"

      - name: Build the App
        run: mvn clean package --file pom.xml

      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ghcr.io/${{ github.repository }}/${{ secrets.DOCKER_CONTAINER_NAME }}:v1.0.0

      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.PAT_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Push Docker Image to GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ secrets.DOCKER_CONTAINER_NAME }}:v1.0.0

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_IP_ADDRESS }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            # Login to GitHub Container Registry
            echo "${{ secrets.PAT_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

            # Pull the Docker image
            docker pull ghcr.io/${{ github.repository }}/${{ secrets.DOCKER_CONTAINER_NAME }}:v1.0.0

            # Stop and remove the existing container
            docker stop ${{ secrets.DOCKER_CONTAINER_NAME }} || true
            docker rm ${{ secrets.DOCKER_CONTAINER_NAME }} || true

            # Run the new container
            docker run -d --name "${{ secrets.DOCKER_CONTAINER_NAME }}" --restart unless-stopped -p 8081:8081 ghcr
            .io/${{ github.repository }}/${{ secrets.DOCKER_CONTAINER_NAME }}:v1.0.0
